hostname     = "kristiankupsch.de"
title        = "Kristian Kupsch"
languageCode = "en-us"
theme        = "hello-friend"
paginate     = 10

[params]
  dateform        = "2 Jan , 2006"
  dateformShort   = "2 Jan "
  dateformNum     = "01-02-2006"
  dateformNumTime = "01-02-2006 15:04"

  # Subtitle for home
  homeSubtitle = "Software Craftsman"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Software Craftsman"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Kristian Kupsch"
    subtitle = "Software Craftsman"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Kristian Kupsch"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = true
  disableJSON = false
  disableSVG = false
  disableXML = false

  [[params.social]]
  name = "xing"
  url = "https://www.xing.com/profile/Kristian_Kupsch/"

  [[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/kristian-kupsch/"

  [[params.social]]
  name = "github"
  url = "https://github.com/kristiankupsch/"

  [[params.social]]
  name = "mail"
  url = "kupschkristian@gmail.com"